site_name: Knowledge Base
site_description: Structured technical notes on software engineering, system design, and programming concepts
site_author: Your Name
site_url: https://sachin141097.github.io/knowledge-base/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md

  - Golang:
      - Basics: golang/basics.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite